#!/bin/bash

function weather() {
  idu=$1
  spot=$2
  spot_id=$3
  year=$4

  date_from="$year-05-30"
  date_to="$year-06-09"

  data="date_from=$date_from&date_to=$date_to&id_spot=$spot_id&step=3&pwindspd=1&psmer=1&ptmp=1&id_model=3&id_stats_type=1"
  mkdir -p $spot
  echo "Spot: $spot and $year >>"
  curl -s 'https://www.windguru.cz/ajax/ajax_archive.php' \
    -H "Cookie: idu=${idu}" \
    --data $data > "${spot}/${spot}_$year".html

  sed -i -e "1s/^/\<b\>$year\<\/b\>\<br\>/" ${spot}/${spot}_${year}.html  

  wkhtmltoimage ${spot}/${spot}_${year}.html ${spot}/${spot}_${year}.jpg

  convert ${spot}/${spot}_${year}.jpg -gravity East -chop 250x0 ${spot}/${spot}_${year}.jpg
}


idu_from_arg=$1

if [[ -z "$idu_from_arg" ]] ; then
  echo "Please provide an idu token!"
  exit 1
fi

## please set spots & spot_ids here manually
## e.g.: 
# spots=("El_Gouna" "Soma_Bay" "Hamata")
# spot_ids=(25164 153754 172696)

if [[ -z "$spots" || -z "$spot_ids" ]] ; then
  echo "Please set both spots & spot_ids in the file manually!"
  exit 1
fi

# cleanup
for spot in "${spots[@]}"
do
  rm -rf $spot
done

for year in 2019 2018 2017 2016 2015 2014
# for year in 2019
do
    echo "Creating for year: $year"
    i=0
    for spot in "${spots[@]}"
    do
      weather $idu_from_arg $spot ${spot_ids[$i]} $year
	  i=$i+1
	done
done

# delete html + html-e files
for spot in "${spots[@]}"
do
  rm ${spot}/*.html ${spot}/*.html-e 2>/dev/null
done
# convert -append El_Gouna/*.jpg El_Gouna/El_Gouna_overview.jpg